% Plot the initialized data

xmlDatei = 'NAME_OF_XML_FILE.xml';
disp('QuickVisualize');
quickVisualizeString = ['QuickVisualize ',xmlDatei];
[returnValue,b]=system(quickVisualizeString);
disp(b);
if returnValue ~= 0
    error(b)
end



if(exist('Patch_Areas.csv','file') && exist('Patch_Vertices.csv','file') && exist('Patch_Temperatures.csv','file'))
    movefile('Patch_*','Init\.')
else
    error('input files have not been generated by quickvisualizer, ask support for help')
end

%%Read in
disp('Reading in csv-files ...');
areas = csvread('Init\Patch_Areas.csv');
vertices = csvread('Init\Patch_Vertices.csv');
f = fopen('Init\Patch_Temperatures.csv');
x = fread(f,1);
if x == '#'
    tempVec = csvread('Init\Patch_Temperatures.csv',2,0 );
else
    tempVec = csvread('Init\Patch_Temperatures.csv' );
end
fclose(f);

disp('Plot the init state');
areas(areas==0) = NaN;
figure('units','normalized','outerposition',[0 0 1 1]);
set(gcf,'Renderer','zbuffer');
view([27 55]);
xlabel('x [m]','fontsize',14);
ylabel('y [m]','fontsize',14);
zlabel('z [m]','fontsize',14);
cb = colorbar('vert');
ylabel(cb,'Temperatur [\circ C]','fontsize',14);
caxis([min(min(tempVec(:, 2:end)))-1,max(max(tempVec(:, 2:end)))+1]);
title(['time: ',num2str(tempVec(1, 1))]);
temperatures = transpose(tempVec(1, 2:end));
set(gca,'DataAspectRatio',[1 1 1]);
patch('Vertices',vertices,'Faces',areas,'FaceColor','flat','FaceVertexCData',temperatures,'Marker','.','MarkerFaceColor','k');

clear areas;
clear vertices;
clear tempVec;
clear temperatures;
clear quickVisualizeString;
clear cb;
clear a;
clear b;
