#!/bin/bash -e

mkdir -p build && cd build

cmake ../ \
-G "CodeBlocks - Unix Makefiles" \
-DUSE_STRING_AND_STREAMS=ON \
-DUSE_UNITTEST=OFF \
-DUSE_ZLIB_COMPRESSION=OFF \
-DUSE_BOOST_MPI=OFF \
-DUSE_BOOST_THREADS=OFF \
-DBUILD_DOT_EXPORT=ON \
-DBUILD_ELECTRICAL_SIMULATION=ON \
-DBUILD_QUICKVERIFICATION=ON \
-DBUILD_SVG_EXPORT=ON \
-DBUILD_THERMAL_ELECTRICAL_SIMUL=ON \
-DBUILD_THERMAL_SIMULATION=ON \
-DBUILD_VISUALIZER=ON \
-D CMAKE_CXX_FLAGS="-D__EXCEPTIONS__=1" # Code smell

make -j$(nproc)

echo "Building docs"
make doc 

